Repository AGH-Narzedzia-Informatyczne-2022-2023/Szostka_z_7, pull requests merged in 2022-11, with the labels that each got.

#9 Creating main.py and some readme changes
  README.md
  main.py
Labels: essential

#10 Add figure images files to the project
  figures images/bB.png
  figures images/bK.png
  figures images/bN.png
  figures images/bQ.png
  figures images/bR.png
  figures images/bp.png
  figures images/wB.png
  figures images/wK.png
  figures images/wN.png
  figures images/wQ.png
  figures images/wR.png
  figures images/wp.png
  figures/bB.png
  figures/bK.png
  figures/bN.png
  figures/bP.png
  figures/bQ.png
  figures/bR.png
  figures/wB.png
  figures/wK.png
  figures/wN.png
  figures/wP.png
  figures/wQ.png
  figures/wR.png
Labels: enhancement, question

#11 Creating chess board
  board.py
Labels: feature, essential

#16 Logo zespołu
  README.md
  logo nr.2.jpg
  logo_ideas/logo nr.1.jpg
  logo_ideas/logo nr.2.jpg
  logo_ideas/logo nr.3.jpg
  logo_ideas/logo nr.4.jpg
Labels: good first issue, feature

#17 Dodanie pomysłów
  Gra z innym graczem i komputerem - Pomysły
Labels: good first issue, feature

#19 Usprawnienia w czytelności projektu
  README.md
  ideas/Gra z innym graczem i komputerem - Pomysły
  ideas/Ogólny plan kodu
  ideas/figures_ideas/bB.png
  ideas/figures_ideas/bK.png
  ideas/figures_ideas/bN.png
  ideas/figures_ideas/bQ.png
  ideas/figures_ideas/bR.png
  ideas/figures_ideas/bp.png
  ideas/figures_ideas/wB.png
  ideas/figures_ideas/wK.png
  ideas/figures_ideas/wN.png
  ideas/figures_ideas/wQ.png
  ideas/figures_ideas/wR.png
  ideas/figures_ideas/wp.png
  ideas/logo_ideas/logo nr.1.jpg
  ideas/logo_ideas/logo nr.2.jpg
  ideas/logo_ideas/logo nr.3.jpg
  ideas/logo_ideas/logo nr.4.jpg
  logo.jpg
Labels: enhancement
